# Example configuration file for configistate

[database]
host = "localhost"
port = 5432
username = "myapp"
# password = "file:///path/to/password.txt"  # Example of file:// variable

[cache]
redis_url = "redis://localhost:6379"
timeout = 30

[app]
debug = true
log_level = "INFO"
max_connections = 100

[features]
enable_logging = true
enable_metrics = false